/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udla.lospythones.sistema.lasacacias.caballos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import udla.lospythones.sistema.lasacacias.BaseDeDatos;

/**
 *
 * @author SARILOLA
 */
public class AgregarHistorial extends javax.swing.JFrame {
    BaseDeDatos db = new BaseDeDatos(); //conexión con la base de datos
    Connection acacias = db.connectToDataBase();

    /**
     * Creates new form AgregarHistorial
     */
    public AgregarHistorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vacuna = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        desparacitacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        enfermedad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar/Editar Historial");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ID del caballo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Vacuna:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        vacuna.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(vacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Desparacitación:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        desparacitacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(desparacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Enfermedad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        enfermedad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(enfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 250, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       boolean i = true;
        boolean confirmar = true;
        while (i) {
            try {
                while (confirmar) {//ingreso de datos
                    int ident = Integer.parseInt(id.getText());

                    //verificar id
                    String verificar = "SELECT * FROM caballo WHERE  idcaballo = '"+ ident +"'";
                    Statement st = acacias.createStatement();
                    ResultSet rs = st.executeQuery(verificar);

                    if (rs.next()){
                        String vacunas = vacuna.getText();
                        String despar = desparacitacion.getText();
                        String enferm = enfermedad.getText();

                        //se insertan los datos en la base de datos
                        String s = "INSERT INTO historialmed (idCaballo, vacuna, desparacitacion, enfermedad) VALUES (?, ?, ?,?)";
                        try (PreparedStatement insertar = acacias.prepareStatement(s)) {
                            insertar.setInt(1, ident); //se ubica información segun el tipo de valor que admite cada columna
                            insertar.setString(2, vacunas);
                            insertar.setString(3, despar);
                            insertar.setString(4, enferm);
                            insertar.executeUpdate(); //actualización
                        } catch (SQLException e) {
                            throw new RuntimeException(e);
                        }

                        int conf = Integer.parseInt(JOptionPane.showInputDialog(null, "La información ingresada es correcta? Una vez ingresada no será posible modificarla. (1. SI - 2.NO)"));
                        if (conf == 1) {
                            confirmar = false;
                        }
                    } else{
                        JOptionPane.showMessageDialog(null, "No hay un caballo con tal id en el criadero...");
                        confirmar = false;
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor valido!");
            } catch (SQLException ex) {
               Logger.getLogger(AgregarHistorial.class.getName()).log(Level.SEVERE, null, ex);
           }

            //iteracion
            int siono = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingresar otro historial? (1. Si - 2.No)"));
            if (siono == 2) {
                setVisible(false);
                i = false;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarHistorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField desparacitacion;
    private javax.swing.JTextField enfermedad;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField vacuna;
    // End of variables declaration//GEN-END:variables
}
